# ┌───────────────────────────────────────────────────────────────┐
# │ AI Expert Toolkit — Jekyll site config (custom domain)       │
# └───────────────────────────────────────────────────────────────┘
title: AI Expert Toolkit
description: Expert reviews, comparisons, and tutorials to help you choose the right AI faster and work smarter.

# Live domain and no baseurl for custom domain
url: https://aiexperttoolkit.com
baseurl: "" # important: empty string

# Build settings
permalink: /:title.html
markdown: kramdown
timezone: Etc/UTC

# Analytics & verification
analytics:
  ga4: G-6E56LGF5M5
  gtm: "" # optional later

verification:
  google: Q2zwZybZQFSXqMBM_ESNzndVqjHGmjyJ3l5ZLu0F2F0
  bing:
  pinterest:

# Icons / manifest
logo:
manifest:
apple_touch_icon:
favicon_png_32:
favicon_png_16:

# Social (optional)
twitter_username:
social_sameas: []

# Feature flags
enable_sitelinks_searchbox: true

# Preconnects (page can override)
preconnect_domains:
  - https://writesonic.com

# Files/directories not published
exclude:
  - README.md
  - SITE_STATE.md
  - manifest.json
  - node_modules
  - vendor

# Plugins (GitHub Pages safe)
plugins:
  - jekyll-sitemap

# Kramdown defaults
kramdown:
  input: GFM

# --- Analytics ---
ga4_measurement_id: G-6E56LGF5M5

# Only exclude the internal checks dashboard from GA
ga_exclude:
  - "/checks.html"
