# _config.yml — AI Expert Toolkit

title: "AI Expert Toolkit"
description: "Expert reviews, comparisons, and tutorials to help you choose the right AI faster and work smarter."
lang: en

# Current live host on GitHub Pages
url: "https://aiexperttoolkit.github.io"
baseurl: "/aiexperttoolkit"

# URLs your pages use (keeps existing pattern like /writesonic-review.html)
permalink: "/:title.html"

# Performance hints used by the layout
preconnect_domains:
  - https://writesonic.com
  - https://www.googletagmanager.com

# Enable the WebSite/SearchAction JSON-LD block in the layout
enable_sitelinks_searchbox: true

# Analytics (read by _layouts/default.html)
analytics:
  ga4: "G-6E56LGF5M5" # ✅ your GA4 Measurement ID
  gtm: "" # leave empty unless you add Google Tag Manager

# Search Console verification (layout pulls this into a <meta> tag)
verification:
  google: "Q2zwZybZQFSXqMBM_ESNzndVqjHGmjyJ3l5ZLu0F2F0"

# Optional fields your layout will include only if present
logo: /assets/ui/favicon.svg # placeholder until you add a proper logo
contact_email: ""
twitter_username:
social_sameas: []

# Build settings
markdown: kramdown
kramdown:
  input: GFM
timezone: UTC

# Keep the build lean
exclude:
  - README.md
  - SITE_STATE.md
  - node_modules
  - vendor
  - Gemfile
  - Gemfile.lock
  - package.json
  - package-lock.json
  # NOTE: Don't list manifest.json here unless you're sure you don't want a <link rel="manifest">.
