name: Pages post-deploy smoke

on:
  workflow_run:
    workflows: ["Deploy site to GitHub Pages (static)"]
    types: [completed]

jobs:
  smoke:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    env:
      BASE_URL: ${{ vars.SITE_BASE_URL || 'https://aiexpertoolkit.com' }}
    steps:
      - name: Probe core endpoints (/, hello-bats, sitemap, robots)
        shell: bash
        run: |
          set -euo pipefail
          urls=("$BASE_URL/" "$BASE_URL/hello-bats.html" "$BASE_URL/sitemap.xml" "$BASE_URL/robots.txt")
          for u in "${urls[@]}"; do
            code="$(curl -s -o /dev/null -w "%{http_code}" "$u")"
            echo "$code  $u"
            [ "$code" = "200" ] || { echo "Expected 200 for $u, got $code" >&2; exit 1; }
          done
          curl -s "$BASE_URL/hello-bats.html" | grep -i "Hello Bats" >/dev/null
